import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { Roboto } from "next/font/google";
import { ThemeToggleProvider } from "./theme";
import Navbar from "./navbar/page";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
    
        <AppRouterCacheProvider>
  
          <ThemeToggleProvider>
            <Navbar/>
                {children}
          </ThemeToggleProvider>
  
        </AppRouterCacheProvider>
 
      </body>
  
    </html>
  );
}
